language: php
php:
  - 5.5
  - 5.6
services: redis-server
before_script:
  - sh -c "wget https://github.com/phpredis/phpredis/archive/develop.zip -O phpredis-develop.zip && unzip phpredis-develop.zip"
  - sh -c "cd phpredis-develop/ && phpize && ./configure && make && make install"
  - sh -c "echo \"extension=redis.so\" >> `php --ini | grep \"Loaded Configuration\" | sed -e \"s|.*:\s*||\"`"
  - composer install --dev
script: phpunit -c test/phpunit.xml