language: php
php:
  - 5.5
  - 5.6
services: redis-server
env:
  - REDIS_STANDALONE=0
  - REDIS_STANDALONE=1
before_script:
  - sh -c "if [ $REDIS_STANDALONE -eq 0 ]; then wget https://github.com/phpredis/phpredis/archive/develop.zip -O phpredis-develop.zip && unzip phpredis-develop.zip; fi"
  - sh -c "if [ $REDIS_STANDALONE -eq 0 ]; then cd phpredis-develop/ && phpize && ./configure && make && make install; fi"
  - sh -c "if [ $REDIS_STANDALONE -eq 0 ]; then echo \"extension=redis.so\" >> `php --ini | grep \"Loaded Configuration\" | sed -e \"s|.*:\s*||\"`; fi"
  - composer install --dev
script: phpunit -c test/phpunit.xml